name: Build Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create metadata files
        run: ./gradlew createMetadataFile || echo "Skipping metadata creation"

      - name: Detect app module directory
        id: detect_app
        run: |
          APP_DIR=$(find . -type f -name build.gradle | grep '/app/build.gradle' | sed 's|/build.gradle||')
          echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
          echo "Detected APP_DIR=$APP_DIR"
          pwd
          echo "APP_DIR full path: $(pdw)/$APP_DIR"

      - name: Generate a temporary keystore
        run: |
          keytool -genkeypair -v \
            -keystore app/release-keystore.jks \
            -storepass password \
            -alias release-key \
            -keypass password \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Fridgey, OU=Fridgey, O=Fridgey, L=City, S=State, C=US"
          echo "Keystore created at:"
          ls -la release-keystore.jks
          pwd
          echo "Full path: $(pwd)/release-keystore.jks"

      - name: Build release APK
        run: |
          ./gradlew :app:assembleRelease \
            -Pandroid.injected.signing.store.file=release-keystore.jks \
            -Pandroid.injected.signing.store.password=password \
            -Pandroid.injected.signing.key.alias=release-key \
            -Pandroid.injected.signing.key.password=password

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: Fridgey-release-apk
          path: app/build/outputs/apk/release/app-release.apk
